### ISSUE TITLE
"Sass compiler not installed" -> Is Sass mandatory ?

### ISSUE THREAD

**Issue by inouire** [mattattui/site-builder#3]
When I initiate a new project with `php site-builder.phar init`
If I try to generate the files with `php site-builder.phar rebuild`, I have this error:

> [InvalidArgumentException]
> Sass compiler not installed, or not configured. Check your config.ini

As I don't want to use Sass I left the field blank in the config.ini file: `sass_path =` but it doesn't seem to work.

Am I doing something wrong ? Or is there a problem with arguments checking ?

**Comment by mattattui** [comment]
There's probably a problem! I'll look into it, sorry about that.

**Comment by mattattui** [comment]
Found it, fixed it (I hope), and released it. Thanks for spotting the issue!

**Comment by inouire** [comment]
You're welcome, glad I could help.
Thank you for making the correction in such short notice.

**Comment by inouire** [comment]
Hello there,
FYI I hit this bug again on my Debian Squeeze when using the last version (downloaded from lazycat.org/download/sitebuilder.phar) 

Possible regression ?

**Comment by mattattui** [comment]
I've rebuilt and uploaded the phar; would you mind checking again?

**Comment by inouire** [comment]
Thanks, it's working now !
