### ISSUE TITLE
Default template not always taken into account ?

### ISSUE THREAD

**Issue by inouire** [mattattui/site-builder#7]
I just noticed a strange behavior towards default template.
Here is my structure

```
index.md
a/
  |_plop.md
b/
  |_plop.md  
```

The two `plop.md` files are the same, and no template is defined in their front matter. So I assume that default template specified in `config.ini` will be used.
`index.md` has a specific template though, specified in the front-matter

But when I rebuild the site, one of the generated file has the good template (default), but the other has the template used by index.md !

Any idea ? Thanks for your help,

**Comment by mattattui** [comment]
Oh dear, how embarrassing. Thanks for spotting that.

**Comment by inouire** [comment]
Thanks for the correction. It's working fine now.
