### ISSUE TITLE
could u pls give a concrete website example?

### ISSUE THREAD

**Issue by luckypoem** [mattattui/site-builder#8]
hi.
i'm a newbie to the template languages,so could u pls give/make a concrete website example for me to clone it?
tks

**Comment by mattattui** [comment]
I'm sorry, I don't recommend anyone use site-builder. It's just a personal and unsupported project. Please have a look at some of the alternative projects mentioned in the [readme](https://github.com/inanimatt/site-builder/blob/master/README.md) or [sculpin](https://sculpin.io/getstarted/). Most of them have default templates and site layouts.
